//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DianShang.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DianziShangwuEntities : DbContext
    {
        public DianziShangwuEntities()
            : base("name=DianziShangwuEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Guest> Guest { get; set; }
        public virtual DbSet<member> member { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<tb_goods> tb_goods { get; set; }
        public virtual DbSet<tb_manager> tb_manager { get; set; }
        public virtual DbSet<tb_order> tb_order { get; set; }
        public virtual DbSet<tb_subType> tb_subType { get; set; }
        public virtual DbSet<tb_superType> tb_superType { get; set; }
        public virtual DbSet<TempStore> TempStore { get; set; }
    }
}
