//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DianShang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class member
    {
        public int ID { get; set; }
        public string truename { get; set; }
        public string name { get; set; }
        public string password { get; set; }
        public string city { get; set; }
        public string cardno { get; set; }
        public string address { get; set; }
        public string postcode { get; set; }
        public string Email { get; set; }
        public string tel { get; set; }
        public string question { get; set; }
        public string answer { get; set; }
    }
}
