//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DianShang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_goods
    {
        public int ID { get; set; }
        public Nullable<int> typeID { get; set; }
        public Nullable<int> type { get; set; }
        public string goodsName { get; set; }
        public string introduce { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<double> nowprice { get; set; }
        public Nullable<long> num { get; set; }
        public string goodsType { get; set; }
        public string newgoods { get; set; }
        public byte[] Image_content { get; set; }
        public Nullable<System.DateTime> INTime { get; set; }
    
        public virtual tb_subType tb_subType { get; set; }
        public virtual tb_superType tb_superType { get; set; }
    }
}
